spring:
  application:
    name: integration

demo:
  apis:
    nominatim: https://nominatim.openstreetmap.org/
    restcountries: https://restcountries.com/v3.1/
    openmeteo: https://api.open-meteo.com/v1/